apiVersion: v1
kind: Service
metadata:
  name: frontend-devops
  namespace: devops
  labels:
    app: frontend-devops
spec:
  type: LoadBalancer
  selector:
    app: frontend-devops
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
